name: Check DCO

on:
  pull_request:

permissions: {}

jobs:
  check-dco:
    name: Check DCO
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: KineticCafe/actions-dco@efa6164fb3608ab18f9b31d16d809ce177541ba4 # v1.3.3
        with:
          exempt-authors: |
            austin@zieglers.ca
